### PR TITLE
Update ESLint to v1.9

### PR DESCRIPTION
**Pull request by saneyuki**
http://eslint.org/blog/2015/11/eslint-v1.9.0-released/

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/453)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7c62fdd has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7c62fdd with merge 058528a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/89782455)

**Pull request merged**
