### PR TITLE
chore(package.json): update dependencies which are related to typescript 

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/695)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit fa73250 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit fa73250 with merge 5bcf5c5...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/141129754)

**Pull request merged**
