### PR TITLE
 refactor(build): split out linker process.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/679)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0d9c1cd has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0d9c1cd with merge 8d5ef2d...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/138866158)

**Pull request merged**
