### PR TITLE
Update ESLint to 0.24.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/248)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit a337821 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit a337821 with merge 0df2042...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/68583373)

**Pull request merged**
