### PR TITLE
Introduce tslint

### LINKED ISSUE #194: Return of the Lint for TypeScript
By #193, we introduced TypeScript compilation to our build chain. But our chain has not get a lint phase for TypeScript yet. We might introduce [tslint][tslint] which is a lint tool for TypeScript.

[tslint]: https://www.npmjs.com/package/tslint

### PR DESCRIPTION
**Pull request by saneyuki**
- Fix #194
- https://github.com/palantir/tslint
- Enable some important rules.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/409)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/409)

**Comment by saneyuki** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: 1 of 15 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/409)

**Comment by saneyuki** [comment]
Reviewed 4 of 4 files at r4, 2 of 2 files at r5, 9 of 9 files at r6, 1 of 1 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/409)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 011a5d9 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 011a5d9 with merge 0927600...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/84708200)

**Pull request merged**
