### PR TITLE
Allow to use undefined when initialize variables.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/658)

### CODE REVIEW

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #671) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #674) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 07a85c2 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 07a85c2 with merge 8b137b5...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/142764461)

**Pull request merged**
