### PR TITLE
chore(travis): Stop to run 'npm prune' & 'npm dedup'

### PR DESCRIPTION
**Pull request by saneyuki**
These combination is very flaky...

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/546)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit efc4251 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit efc4251 with merge b401efe...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/103814223)

**Pull request merged**
