### PR TITLE
chore(package.json) update packages

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/599)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d850918 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d850918 with merge b440a6c...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/115681184)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #599) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
