### PR TITLE
refactor(eslint): increase portability of eslintrc

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/674)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 82fe31f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 82fe31f with merge 2c73eb6...

**Comment by saneyuki** [comment]
@dokidokivisual r-

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/137992071)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 1aaa908 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 1aaa908 with merge 0910c59...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/137992493)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 3c882f2 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 3c882f2 with merge 136ee5a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/137992924)

**Pull request merged**
