### PR TITLE
Update eslint-plugin-react to v3.7.x

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/450)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 25ac1a9 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 25ac1a9 with merge 4c03def...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/89440006)

**Pull request merged**
