### PR TITLE
[client] Define Message interface's members.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/307)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 01fffe6 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 01fffe6 with merge c7a0e5d...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/75731491)

**Pull request merged**
