### PR TITLE
fix(client): fix the bug of autocomplete

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/700)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 86ac86f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 86ac86f with merge 757d6fb...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/142507357)

**Pull request merged**
