### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/477)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 26f74f3 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 26f74f3 with merge f1e7c67...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/92102238)

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 26f74f3 with merge d521e24...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/92102956)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit c778a4f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit c778a4f with merge f8c387b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/92200130)

**Pull request merged**
