### PR TITLE
Make index.html to React Component rendered on the server side.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/269)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 15 of 15 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/269)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d6b8ce4 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d6b8ce4 with merge 6a8ea7d...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/71583898)

**Pull request merged**
