### PR TITLE
chore(jsconfig.json): specify stdlib version explicitly.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/607)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 8e10a5c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 8e10a5c with merge a9e5f8c...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/119371808)

**Pull request merged**
