### PR TITLE
chore(package.json): update packages

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/589)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 572229f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 572229f with merge fcb79c1...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/113341964)

**Pull request merged**
