### PR TITLE
refactor(build): specify '--project' tsc option explicitly.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/717)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 90eaf1e has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 90eaf1e with merge 86a8c7c...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/145049807)

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/145051002)

**Pull request merged**
