### PR TITLE
Update some packages

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/561)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 5dbc03c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 5dbc03c with merge 6f77807...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/104547443)

**Pull request merged**
