### PR TITLE
Use template literal to represent csp directive values

### PR DESCRIPTION
**Pull request by Constellation**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/276)

### CODE REVIEW

**Comment by Constellation** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d41b0d5 has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d41b0d5 with merge c01a7bb...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/71661468)

**Pull request merged**
