### PR TITLE
Fix the typescript compiler error

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/294)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 2bdebbf has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 2bdebbf with merge 20e91ce...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74438681)

**Pull request merged**
