### PR TITLE
refactor(FetchDriver): keep FetchDriver's abstraction only origin

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/684)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 5578cfb has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 5578cfb with merge 1ab5d04...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/139020440)

**Pull request merged**
