### PR TITLE
chore(package.json): update packages

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/573)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 1f59814 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 1f59814 with merge 7e5c55f...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/108207263)

**Pull request merged**
