### PR TITLE
Rename ViewController -> View

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/413)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit c94822a has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit c94822a with merge bc9dba7...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/84726679)

**Pull request merged**
