### PR TITLE
refactor(tslint): use '--project' option

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/711)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 8b181f5 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 8b181f5 with merge ceaf00c...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/144763227)

**Pull request closed without merging**
