### PR TITLE
refactor(dir): make dist directories explicitly

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/662)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit dced1eb has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit dced1eb with merge a5a58fa...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/133442217)

**Pull request merged**
