### PR TITLE
feat(server): set session id for request.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/640)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 35e907a has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 35e907a with merge ba9e1e6...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/127718625)

**Pull request merged**
