### PR TITLE
chore(TypeScript): Enable 'strictNullChecks' option

### PR DESCRIPTION
**Pull request by saneyuki**
## Summary

This tries to enable [`--strictNullChecks` option](https://github.com/Microsoft/TypeScript/pull/7140) of TypeScript compiler.

## Related

- [Non-nullable types by ahejlsberg · Pull Request #7140 · Microsoft/TypeScript](https://github.com/Microsoft/TypeScript/pull/7140)
  - [Non-strict type checking · Issue #7489 · Microsoft/TypeScript](https://github.com/Microsoft/TypeScript/issues/7489)
  - [[Request for feedback] Nullable types, `null` and `undefined` · Issue #7426 · Microsoft/TypeScript](https://github.com/Microsoft/TypeScript/issues/7426)
- [Control flow based type analysis by ahejlsberg · Pull Request #8010 · Microsoft/TypeScript](https://github.com/Microsoft/TypeScript/pull/8010)

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/604)

### CODE REVIEW

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #608) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 9660b36 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 9660b36 with merge 25ed88b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/127797988)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #604) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
