### PR TITLE
fix(FetchDriver): add comment the format of origin.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/704)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 299ae96 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 299ae96 with merge 8986868...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/142654212)

**Pull request merged**
