### PR TITLE
client: Enable babel's 'utility.inlineEnvironmentVariables'.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/433)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit a5a48c7 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit a5a48c7 with merge fb507e4...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/87387135)

**Pull request merged**
