### PR TITLE
Update TypeScript compiler to 1.7.0-dev.20151006.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/406)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7be9bfe has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7be9bfe with merge 537f260...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/84011466)

**Pull request merged**
