### PR TITLE
chore(ESLint): introduce eslint-plugin-node

### PR DESCRIPTION
**Pull request by saneyuki**
We'd like to detect importing missing files from JavaScript.

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/601)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e0e2462 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e0e2462 with merge 83624f0...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/116606989)

**Pull request merged**
