### PR TITLE
refactor(GeneralSetting): define GeneralSettingViewModel

### PR DESCRIPTION
**Pull request by saneyuki**
...and use it.

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/648)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e741996 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e741996 with merge 85733c4...

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e741996 has been approved by `saneyuki`

**Pull request merged**
