### PR TITLE
Update some packages.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/515)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 503e68d has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 503e68d with merge fc8eb1e...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/96310888)

**Pull request merged**
