### PR TITLE
Import Rx when it's used

### PR DESCRIPTION
**Pull request by Constellation**
Some TS files do not contain Rx as the dependencies.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/258)

### CODE REVIEW

**Comment by Constellation** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 6225885 has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 6225885 with merge 757e7e1...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/70270861)

**Pull request merged**
