### PR TITLE
Reduce to use lodash

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/268)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 6 of 23 files at r1.
Review status: 6 of 23 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/268)

**Comment by saneyuki** [comment]
Reviewed 10 of 23 files at r1, 1 of 1 files at r2.
Review status: 17 of 23 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/268)

**Comment by saneyuki** [comment]
Reviewed 6 of 23 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/268)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 342d9e9 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 342d9e9 with merge f2fffc8...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/71573891)

**Pull request merged**
