### PR TITLE
Update babel to 6.3

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/513)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 9ceec6f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 9ceec6f with merge 6f9133e...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/95140394)

**Pull request merged**
