### PR TITLE
chore(eslint): update to 2.8

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/619)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit db19ed9 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit db19ed9 with merge f25c0b2...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/123719517)

**Pull request merged**
