### PR TITLE
refactor(server): move view old templates to view/classic/

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/550)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit cfe928d has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit cfe928d with merge 3422e9a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/104000155)

**Pull request merged**
