### PR TITLE
Update eslint-plugin-react to v3.6.x

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/427)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7422368 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7422368 with merge 35f37a4...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/86536674)

**Pull request merged**
