### PR TITLE
chore(eslint): update to 2.3

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/590)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 30cc148 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 30cc148 with merge 1c9c64a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/113849522)

**Pull request merged**
