### PR TITLE
Update eslint-plugin-react

### PR DESCRIPTION
**Pull request by saneyuki**
- https://github.com/yannickcr/eslint-plugin-react/releases/tag/v3.11.0
  - https://github.com/yannickcr/eslint-plugin-react/releases/tag/v3.11.1
  - https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-handler-names.md

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/506)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 75e3bd6 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 75e3bd6 with merge 5195e8d...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/93852372)

**Pull request merged**
