### PR TITLE
chore(package.json): update eslint to 2.5

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/606)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 717f5bb has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 717f5bb with merge 5295891...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/118921890)

**Pull request merged**
