### PR TITLE
Update TypeScript Compiler to 2cd2a4acc6d09bda93c619b82c33e441f89c88a6

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/245)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 4886016 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 4886016 with merge f43b40c...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/68308084)

**Pull request merged**
