### PR TITLE
Make CookieDriver.get() returns Option<T>.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/394)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 82c87a0 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 82c87a0 with merge fdce0e7...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/82457182)

**Pull request merged**
