### PR TITLE
Enable Stateless Function Components infrastructure which TypeScript supports officially

### PR DESCRIPTION
**Pull request by saneyuki**
the design details in TypeScript: https://github.com/Microsoft/TypeScript/issues/5478

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/512)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual try

**Comment by dokidokivisual** [comment]
:hourglass: Trying commit 704f9a9 with merge b4339b8...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/94418820)

**Comment by saneyuki** [comment]
@dokidokivisual +r

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 786057b has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 786057b with merge 47accaa...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/94421606)

**Pull request merged**
