### PR TITLE
chore(package.json): update dependencies

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/623)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7a56bbb has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7a56bbb with merge 0641cf8...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/124949597)

**Pull request merged**
