### PR TITLE
Write all eslint's rules explicitly

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/543)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 29e2065 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 29e2065 with merge 82868d7...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/103042094)

**Pull request merged**
