### PR TITLE
Update typescript compiler to 1.8.0-dev.20151017

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/425)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit da908f1 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit da908f1 with merge 2ae67d7...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/85876078)

**Pull request merged**
