### PR TITLE
Update TypeScript compiler to 1.7.0-dev.20151014.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/417)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 4bc28bb has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 4bc28bb with merge ef95eea...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/85448981)

**Pull request merged**
