### PR TITLE
 Add 'js-' prefix to attrubite value which is touched from script form input-form.

### PR DESCRIPTION
**Pull request by saneyuki**
#153

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/293)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit afd0741 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit afd0741 with merge 9dc9905...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74430336)

**Pull request merged**
