### PR TITLE
Use tslint's latest stable.

### PR DESCRIPTION
**Pull request by saneyuki**
We don't need to use the development version.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/461)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 2f1b063 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 2f1b063 with merge 1e3c9df...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/90664638)

**Pull request merged**
