### PR TITLE
client: Define ChannelId/NetworkId type

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/452)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0b5fa8f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0b5fa8f with merge 27dc771...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/89631261)

**Pull request merged**
