### PR TITLE
refactor(build): use command file which are installed in node_modules/.bin

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/718)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 4ecee6a has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 4ecee6a with merge 1c6bc77...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/145052498)

**Pull request merged**
