### PR TITLE
refactor(ExIterable): remove Operator interface

### PR DESCRIPTION
**Pull request by saneyuki**
This moves to the design based on an inheritance.

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/690)

### CODE REVIEW

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #691) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #693) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@dokidokivisual try

**Comment by dokidokivisual** [comment]
:hourglass: Trying commit 6f065d9 with merge 78c6ebe...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/142760649)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #745) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request closed without merging**
