### PR TITLE
chore(react): update to 15.0.0-rc.1

### PR DESCRIPTION
**Pull request by saneyuki**
https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/594)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit a441e93 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit a441e93 with merge cfa5658...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/114412803)

**Pull request merged**
