### PR TITLE
eslint: Add why we extends the recommended rule set.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/501)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit db5acf4 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit db5acf4 with merge ed157d8...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/93468146)

**Pull request merged**
