### PR TITLE
Update type definitions

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/555)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit a34a8d8 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit a34a8d8 with merge 7865f5b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/104013377)

**Pull request merged**
