### PR TITLE
Fix some regression by #279

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/282)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 4acd8dc has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 4acd8dc with merge 7b491d2...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/73684850)

**Pull request merged**
