### PR TITLE
Update Rx to v3.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/287)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7676b3e has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7676b3e with merge 35f6353...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74414299)

**Pull request merged**
