### PR TITLE
Update eslint & related packages

### PR DESCRIPTION
**Pull request by saneyuki**
## eslint-plugin-react

https://github.com/yannickcr/eslint-plugin-react

## eslint 
- http://eslint.org/blog/2015/11/eslint-v1.10.0-released/
  - http://eslint.org/docs/user-guide/configuring#configuration-file-formats
- http://eslint.org/blog/2015/11/eslint-v1.10.1-released

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/485)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit fe4fa6c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit fe4fa6c with merge 6562a5f...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/92403605)

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit fe4fa6c with merge 68c0684...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/92403876)

**Pull request merged**
