### PR TITLE
Use 'exclude' of tsconfig.json instead of 'files'.

### PR DESCRIPTION
**Pull request by saneyuki**
- see: https://github.com/Microsoft/TypeScript/wiki/tsconfig.json
- This change makes more friendly for some IDE (e.g. Visual Studio Code).

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/460)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d2a16cf has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d2a16cf with merge a5d9266...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/90664156)

**Pull request merged**
