### PR TITLE
feat(ExIterable): add the specialized impl for filter().map()

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/692)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 5a7681d has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 5a7681d with merge 7f501df...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/140245723)

**Pull request merged**
