### PR TITLE
Move client/script/store -> client/script/output/viewmodel

### PR DESCRIPTION
**Pull request by saneyuki**
#253

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/255)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 4d372dd has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 4d372dd with merge e8dd4ab...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/69566646)

**Pull request merged**
