### PR TITLE
chore(package.json): update eslint to v2.9

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/632)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit c8c09ca has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit c8c09ca with merge 8554419...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/127169471)

**Pull request merged**
