### PR TITLE
chore(tsc): disable suppressImplicitAnyIndexErrors to ban an implicit reflection

### PR DESCRIPTION
**Pull request by saneyuki**
implicit reflection is evil and challenge to type safety.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/583)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d1c0c34 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d1c0c34 with merge 2d2406f...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/110628510)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 9150704 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 9150704 with merge fcbc185...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/110629275)

**Pull request merged**
