### PR TITLE
Update typescript compiler to 1.8.0-dev.20151121

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/488)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit fcdce87 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit fcdce87 with merge 95690af...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/92446200)

**Pull request merged**
