### PR TITLE
Add '.input-form' selector to rename '#form' selector.

### PR DESCRIPTION
**Pull request by saneyuki**
- This also adds 'js-' prefix to attrubite value which is touched from script.
- see #153

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/292)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 1d740e1 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 1d740e1 with merge 3311900...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74427431)

**Pull request merged**
