### PR TITLE
chore(package.json): update typescript compiler

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/667)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit c2187a2 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit c2187a2 with merge f20788c...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/134643587)

**Pull request merged**
