### PR TITLE
chore(package.json): update eslint to 2.6

### PR DESCRIPTION
**Pull request by saneyuki**
http://eslint.org/blog/2016/04/eslint-v2.6.0-released

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/609)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 4118b3e has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 4118b3e with merge b0dfb5b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/120445779)

**Pull request merged**
