### PR TITLE
Upgrade browserify to v11

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/267)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d5e6f26 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d5e6f26 with merge 367a150...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/71561325)

**Pull request merged**
