### PR TITLE
chore(ESLint): update to 2.0.0-beta.3

### PR DESCRIPTION
**Pull request by saneyuki**
http://eslint.org/blog/2016/01/eslint-v2.0.0-beta.3-released/

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/566)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit f0d90a8 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit f0d90a8 with merge 9332b89...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/105907596)

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit f0d90a8 with merge ef5f8bf...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/105907946)

**Pull request merged**
