### PR TITLE
Stop default export in client code without a singleton instance.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/399)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 11beab5 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 11beab5 with merge 307f1a3...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/82619910)

**Pull request merged**
