### PR TITLE
[client] Move /model -> /domain.

### PR DESCRIPTION
**Pull request by saneyuki**
#253

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/259)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 5262e31 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 5262e31 with merge aaee3d2...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/70539372)

**Pull request merged**
