### PR TITLE
Single cut DomainState

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/250)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 28afd57 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 28afd57 with merge b4d6633...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/68586542)

**Pull request merged**
