### PR TITLE
Ignore /.vscode dir until we add a configuration for vscode.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/472)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit eb22d65 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit eb22d65 with merge 451a10a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/91835298)

**Pull request merged**
