### PR TITLE
Update TypeScript compiler to 1.7.0-dev.20150929.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/401)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit ef4a616 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit ef4a616 with merge a0cad70...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/82753478)

**Pull request merged**
