### PR TITLE
Add missing license headers

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/285)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 8 of 11 files at r1.
Review status: 8 of 11 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/285)

**Comment by saneyuki** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/285)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 960c5b0 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 960c5b0 with merge dec0458...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/73697967)

**Pull request merged**
