### PR TITLE
Import 'rx' module correctly.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/398)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit fbea686 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit fbea686 with merge ebc90af...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/82615049)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #398) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
