### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/532)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 65126e4 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 65126e4 with merge a84b5ea...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/100850262)

**Pull request merged**
