### PR TITLE
[client] Add MessageGateway.partFromChannel().

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/308)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 645bc30 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 645bc30 with merge fea522e...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/75734902)

**Pull request merged**
