### PR TITLE
Add exclude field to jsconfig.json.

### PR DESCRIPTION
**Pull request by saneyuki**
This is introduced by VS Code 0.7 https://code.visualstudio.com/Updates

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/302)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 8195937 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 8195937 with merge 46e5468...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/75663732)

**Pull request merged**
