### PR TITLE
chore(package.json): update dependencies.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/708)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0298823 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0298823 with merge ba67ca4...

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request is currently being tested. If there's no response from the continuous integration service, you may use `retry` to trigger a build again.

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0298823 has been approved by `saneyuki`

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0298823 with merge 29f507b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/143576579)

**Pull request merged**
