### PR TITLE
Stop default export dispatchers.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/400)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0d2fa5a has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0d2fa5a with merge 5ca6f6a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/82622199)

**Pull request merged**
