### PR TITLE
Update handlebar to 3.0.3

### PR DESCRIPTION
**Pull request by Constellation**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/236)

### CODE REVIEW

**Comment by Constellation** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 22301f0 has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 22301f0 with merge a4fcf61...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/66087615)

**Pull request merged**
