### PR TITLE
client: Implement basic logic for reactified sidebar

### PR DESCRIPTION
**Pull request by saneyuki**
see also: #191

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/483)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 2 of 3 files at r1.
Review status: 1 of 7 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/483)_

**Comment by saneyuki** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 7 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/483)_

**Comment by saneyuki** [comment]
Reviewed 6 of 6 files at r2.
Review status: 5 of 7 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/483)_

**Comment by saneyuki** [comment]
Reviewed 1 of 1 files at r3.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/483)_

**Comment by saneyuki** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/483)_

**Comment by saneyuki** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/483)_

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e1ad2e9 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e1ad2e9 with merge 123e9c4...

**Comment by saneyuki** [comment]
@dokidokivisual r-

**Pull request merged**
