### PR TITLE
Update TypeScript Compiler to 2cb0dfd99dc2896958b75e44303d8a7a32e5dc33.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/239)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit dcf3e60 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit dcf3e60 with merge 56d6f67...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/66532181)

**Comment by Constellation** [comment]
ちゃんと dokidokivisual commit bot が動いてる

**Pull request merged**
