### PR TITLE
Update the runtime to io@v3.x

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/289)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 87994bf has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 87994bf with merge 7ada2cf...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74417674)

**Pull request merged**
