### PR TITLE
Lock RxJS 3.0.0

### PR DESCRIPTION
**Pull request by saneyuki**
This is workaround fix for https://github.com/Reactive-Extensions/RxJS/issues/857

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/305)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 62951ef has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 62951ef with merge ed05893...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/75670820)

**Pull request merged**
