### PR TITLE
remove needless .eslintrc

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/624)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 4ba7609 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 4ba7609 with merge 0057469...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/125010500)

**Pull request merged**
