### PR TITLE
Add `ViewContext` interface.

### PR DESCRIPTION
**Pull request by saneyuki**
_ViewContext_ is a unit of a view content area and has a lifecycle
itself.

This terminology is inspired by Android's Activity model
and Windows' UWP app lifecycle.

This only provide a lifecycle of view context,
does not manage any dependencies. Dependencies are managed
by an application layer for each application as most suitable style.

An active context ensures:

  - You have an ownership of the view content area under the given mount point.
  - You can render something to the mount point if you are called.

see also #253, #336

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/530)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit b03b8f8 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit b03b8f8 with merge c39b6e1...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/99852606)

**Pull request merged**
