### PR TITLE
Add 'npm run gulp' command

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/290)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit b0301c7 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit b0301c7 with merge b0fcf82...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74421212)

**Pull request merged**
