### PR TITLE
Update browserify to v13

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/537)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit f0643e3 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit f0643e3 with merge 90ac9ab...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/101300660)

**Pull request merged**
