### PR TITLE
Change the dist directory structure.

### PR DESCRIPTION
**Pull request by saneyuki**
retry #551

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/552)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d6907c5 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d6907c5 with merge 153d2b5...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/104002737)

**Pull request merged**
