### PR TITLE
Update eslint-plugin-react

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/521)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e0b83fe has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e0b83fe with merge 2769e60...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/97376028)

**Pull request merged**
