### PR TITLE
refactor(uri): create instant parser

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/714)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 59105ea has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 59105ea with merge 06454f5...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/144817066)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit f61570b has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit f61570b with merge 05be565...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/144897038)

**Pull request merged**
