### PR TITLE
Rename files which includes JSX syntax to `***.jsx`

### PR DESCRIPTION
**Pull request by saneyuki**
Visual Studio Code will handles their syntax highlight correctly by this change.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/395)

### CODE REVIEW

**Comment by Constellation** [comment]
@dokidokivisual:

r+!

**Comment by Constellation** [comment]
@dokidokivisual r=me

**Comment by dokidokivisual** [comment]
:pushpin: Commit 6835fa9 has been approved by `me`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 6835fa9 with merge 2d8c904...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/82463651)

**Pull request merged**
