### PR TITLE
Switch to webpack from browserify

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/652)

### CODE REVIEW

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #653) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[webpack.config.js, line 19 \[r1\]](https://reviewable.io:443/reviews/karen-irc/karen/652#-KKhkG_5xsGmfd3yvtK7:-KKhkG_5xsGmfd3yvtK8:-1542324587) ([raw file](https://github.com/karen-irc/karen/blob/6bf536128e4a4130a60333e93a2ec3ee66c34d0e/webpack.config.js#L19)):*
> ```JavaScript
> 
> let babelPlugins = [
> /* FIXME:
> ```

remove this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/652)*

**Comment by saneyuki** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/build/script.js, line 85 \[r1\]](https://reviewable.io:443/reviews/karen-irc/karen/652#-KKhkpukY01lMT0I781s:-KKhkpukY01lMT0I781t:1983442879) ([raw file](https://github.com/karen-irc/karen/blob/6bf536128e4a4130a60333e93a2ec3ee66c34d0e/tools/build/script.js#L85)):*
> ```JavaScript
>             KAREN_ENTRY_POINT: entryPoint,
>             KAREN_CLIENT_DIST_DIR: distDir,
>         }),
> ```

Don't pass all envs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/652)*

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #681) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/652)*

**Comment by saneyuki** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/652)*

**Pull request merged**
