### PR TITLE
chore(jsconfig.json): follow up #662

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/665)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 08fb7c4 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 08fb7c4 with merge 82a0dc3...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/133979455)

**Pull request merged**
