### PR TITLE
chore(package.json): update dependencies.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/675)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0a63f9b has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0a63f9b with merge 29446d8...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/138614026)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0ba0e9a has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0ba0e9a with merge 7fb0c78...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/138614483)

**Pull request merged**
