### PR TITLE
chore(typings): update typings to 1.0

### PR DESCRIPTION
**Pull request by saneyuki**
## See more

- https://github.com/typings/typings
  - https://github.com/typings/typings/releases
- https://github.com/typings/registry

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/653)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit da9622e has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit da9622e with merge fb4b3e0...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/130760891)

**Pull request merged**
