### PR TITLE
chore(typings): update to v0.7

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/596)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d18ef4f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d18ef4f with merge d974a22...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/115028089)

**Pull request merged**
