### PR TITLE
Add the dokidokivisual commit bot's repository to README.md

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/387)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 5a2458e has been approved by `saneyuki`

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Pull request merged**
