### PR TITLE
chore(typescript): update to 1.9.0-dev.20160222

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/584)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0e69d60 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0e69d60 with merge a068e24...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/110922230)

**Comment by Constellation** [comment]
Maybe, during evening, dokidokivisual cq does not respond to requests because OpenShift was under maintenance. Now, cq is working.

**Comment by saneyuki** [comment]
@Constellation Thank you for the attention

**Pull request merged**
