### PR TITLE
Add some observable point to models

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/251)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e533cbe has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e533cbe with merge 73bb21b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/68608233)

**Pull request merged**
