### PR TITLE
Remove needless call 'jQuery.data()'.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/435)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 5f18f2c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 5f18f2c with merge 53de193...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/87601237)

**Pull request merged**
