### PR TITLE
Reduce to use Handlebars

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/271)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 2 of 2 files at r1.
Review status: 2 of 34 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/271)

**Comment by saneyuki** [comment]
Reviewed 8 of 8 files at r2, 24 of 24 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/271)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e15d8b0 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e15d8b0 with merge de70a55...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/71646663)

**Pull request merged**
