### PR TITLE
[client] Use urijs hosted in npm.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/410)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 30021aa has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 30021aa with merge 54c092f...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/84711531)

**Pull request merged**
