### PR TITLE
Update ESLint to v1.7.x

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/426)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit ef9f0b4 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit ef9f0b4 with merge bfd05c2...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/85964452)

**Pull request merged**
