### PR TITLE
Upgrade ESLint to v1.8.x

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/446)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 38db5c9 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 38db5c9 with merge 04b8c14...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/88730531)

**Pull request merged**
