### PR TITLE
chore(package): update dependencies, rxjs, eslint-plugin-node

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/655)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 28609ce has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 28609ce with merge bacfe55...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/132098443)

**Pull request merged**
