### PR TITLE
[client] Remove jQuery stickyscroll plugin.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/299)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 10abb74 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 10abb74 with merge 8852425...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74470016)

**Pull request merged**
