### PR TITLE
 client: Remove needless jQuery usages.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/508)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0808b19 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0808b19 with merge a7c33a8...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/93871506)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 29e6222 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 29e6222 with merge 43404c5...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/93871599)

**Pull request merged**
