### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/306)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit b0dffa9 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit b0dffa9 with merge 8d889bc...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/75673577)

**Pull request merged**
