### PR TITLE
chore(package.json): update typescript compiler

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/677)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 24f5ac3 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 24f5ac3 with merge 9131e4d...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/138803256)

**Pull request merged**
