### PR TITLE
Update react & react-dom to v0.14 stable

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/407)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 853c704 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 853c704 with merge f5449d0...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/84170651)

**Pull request merged**
