### PR TITLE
[client] Use HTMLElement.insertAdjacentHTML

### PR DESCRIPTION
**Pull request by saneyuki**
retry #418

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/430)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit ba03d75 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit ba03d75 with merge cac3ee5...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/87384400)

**Pull request merged**
