### PR TITLE
[client] Add MessageGateway.joinChannel.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/309)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0927c7f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0927c7f with merge 763ece6...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/75739041)

**Pull request merged**
