### PR TITLE
client: Move the autocompletion logic to InputBoxView.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/507)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 347cb4f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 347cb4f with merge a92c91b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/93865648)

**Pull request merged**
