### PR TITLE
Update eslint-plugin-react to v3.8

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/455)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 4e75866 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 4e75866 with merge 69e277d...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/90446647)

**Pull request merged**
