### PR TITLE
Disable some transforms for server

### PR DESCRIPTION
**Pull request by saneyuki**
[iojs v2.0.0](https://github.com/iojs/io.js/blob/master/CHANGELOG.md#2015-05-04-version-200-rvagg) native support some ES6 features. so we can use them without [transforms](https://babeljs.io/docs/usage/transformers/).

### CODE REVIEW

**Comment by saneyuki** [comment]
@Constellation how do you think about these? I concern about some ES6 options are not implemented in V8's compiler infrastructure.

**Comment by Constellation** [comment]
@saneyuki 

This is the time to write the first test, I think!

**Comment by saneyuki** [comment]
@Constellation what from should we begin?

**Comment by Constellation** [comment]
Is the test compiled by `babel`? If so, using rest parameter in test makes sure that it works.

**Comment by saneyuki** [comment]
Our test code has not been compiled by babel yet.

**Comment by Constellation** [comment]
Ah, ok. Maybe, just adding them to blacklist works I think :)

**Comment by saneyuki** [comment]
oops! I had some misunderstanding. rest parameter and computed property are still behind a flag.

**Comment by saneyuki** [comment]
> Ah, ok. Maybe, just adding them to blacklist works I think :)

Yes. This works will be just to do test.

**Pull request merged**
