### PR TITLE
Merge utils/ and tools/.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/490)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 480ad78 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 480ad78 with merge a53c0b1...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/92451081)

**Pull request merged**
