### PR TITLE
Change the dist directory structure.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/551)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit ba183c6 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit ba183c6 with merge 1725931...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/104001529)

**Pull request merged**
