### PR TITLE
[client] Handle content-area close button in MessageContentViewController.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/412)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit dcbc179 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit dcbc179 with merge e130f26...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/84724796)

**Pull request merged**
