### PR TITLE
refactor(eslintrc): remove needless recommended rules

### PR DESCRIPTION
**Pull request by saneyuki**
We need not load them now.

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/602)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 8710380 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 8710380 with merge d5997fa...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/116607308)

**Pull request merged**
