### PR TITLE
Server files with using gzip compression.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/261)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 20d5908 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 20d5908 with merge 9f88286...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/70542807)

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7e45b5c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7e45b5c with merge 3ddeb20...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/70543119)

**Pull request merged**
