### PR TITLE
[client] Handle to update a nickname in InputBoxView.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/416)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit a801598 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit a801598 with merge 0718bf4...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/84852990)

**Pull request merged**
