### PR TITLE
refactor(ReactiveProperty): introduce 'ReactiveProperty<T>'.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/625)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit fb39f5c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit fb39f5c with merge e11d239...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/125395236)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #625) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
