### PR TITLE
chore(package.json): update dependencies

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/723)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 9a52f99 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 9a52f99 with merge b14cc98...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/149101264)

**Pull request merged**
