### PR TITLE
test(ExIterable): add testcase for flatmap.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/688)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 37b75c8 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 37b75c8 with merge 394f83a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/140225703)

**Pull request merged**
