### PR TITLE
chore(typings): update d.ts

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/618)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 6f09a29 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 6f09a29 with merge 3ec6796...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/122878160)

**Pull request merged**
