### PR TITLE
Update TypeScript compiler to 1.8.0-dev.20151026.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/434)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 1fcb77b has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 1fcb77b with merge f8986db...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/87561299)

**Pull request merged**
