### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/464)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 73a167a has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 73a167a with merge b5a8602...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/91115590)

**Pull request merged**
