### PR TITLE
chore(typings): use the d.ts loading system which is builtin tsc.

### PR DESCRIPTION
**Pull request by saneyuki**
- [The Future of Declaration Files | TypeScript](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/)
- [Improve Declaration File Acquisition · Issue #9184 · Microsoft/TypeScript · GitHub](https://github.com/Microsoft/TypeScript/issues/9184)

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/672)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/672)*

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #681) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/672)*

**Comment by saneyuki** [comment]
Reviewed 2 of 5 files at r3.
Review status: 13 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/672)*

**Comment by saneyuki** [comment]
Reviewed 3 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/672)*

**Pull request merged**
