### PR TITLE
Update TypeScript compiler to 1.8.0-dev.20151128

### PR DESCRIPTION
**Pull request by saneyuki**
see also #503

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/504)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e7d6022 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e7d6022 with merge 8fd02e4...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/93773627)

**Pull request merged**
