### PR TITLE
Various clean up

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/467)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e8e13bb has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e8e13bb with merge d0c2e4c...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/91124137)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 3f23f31 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 3f23f31 with merge 50b45a9...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/91124578)

**Pull request merged**
