### PR TITLE
chore(typings): introduce node.d.ts

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/627)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 2f0ff46 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 2f0ff46 with merge c29407e...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/125882927)

**Pull request merged**
