### PR TITLE
chore(typings): Exclude typings/main.

### PR DESCRIPTION
**Pull request by saneyuki**
We only includes `typings/main.ts`

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/565)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit b27e8ac has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit b27e8ac with merge c10d214...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/105433032)

**Pull request merged**
