### PR TITLE
refactor(gulpfile.js): split out each build functions.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/592)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit ea803e9 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit ea803e9 with merge d3e1489...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/114263641)

**Pull request merged**
