### PR TITLE
Update babel related packages.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/456)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit ebdc85f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit ebdc85f with merge 3249495...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/90603609)

**Pull request merged**
