### PR TITLE
chore(package.json): update packages

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/614)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit a987b52 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit a987b52 with merge 8ce49c8...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/121393349)

**Pull request merged**
