### PR TITLE
chore(ESLint): update to 2.0.0-rc.0

### PR DESCRIPTION
**Pull request by saneyuki**
http://eslint.org/blog/2016/02/eslint-v2.0.0-rc.0-released

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 3ac1ca9 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 3ac1ca9 with merge 716a519...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/106661663)

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 3ac1ca9 with merge 0945e16...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/106661835)

**Pull request merged**
