### PR TITLE
feat(TypeScript): enable 'noImplicitThis'

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/616)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 100aee7 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 100aee7 with merge 4707eeb...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/122723215)

**Pull request merged**
