### PR TITLE
Remove client/js/libs/jquery/bootstrap.js

### PR DESCRIPTION
**Pull request by saneyuki**
In our current codebase, we cannot use bootstrap's javascript features.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/298)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit b69204d has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit b69204d with merge 669ad32...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74456534)

**Pull request merged**
