### PR TITLE
Move client/{dist,__obj} under dist/client

### PR DESCRIPTION
**Pull request by Constellation**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/211)

### CODE REVIEW

**Comment by Constellation** [comment]
Review status: 0 of 12 files reviewed, 3 unresolved discussions, some commit checks pending.

---

<sup>**[server/Package.js, line 32 \[r1\]](https://reviewable.io:443/reviews/karen-irc/karen/211#-JqpvfzDmfv2o1YHa-4I)** ([raw file](https://github.com/karen-irc/karen/blob/ef160d88cfd419eccd7f7cbc0fe0ff345532fa2a/server/Package.js#L32)):</sup>
Hide dirty path calculation into this module.

---

<sup>**[server/plugins/irc-events/ctcp.js, line 3 \[r1\]](https://reviewable.io:443/reviews/karen-irc/karen/211#-Jqpvnh_bG-QwMu9tV89)** ([raw file](https://github.com/karen-irc/karen/blob/ef160d88cfd419eccd7f7cbc0fe0ff345532fa2a/server/plugins/irc-events/ctcp.js#L3)):</sup>
Haha. Maybe, this was already broken before this patch :D

---

<sup>**[server/server.js, line 30 \[r1\]](https://reviewable.io:443/reviews/karen-irc/karen/211#-JqpvSPtFkvQWV8bDAu3)** ([raw file](https://github.com/karen-irc/karen/blob/ef160d88cfd419eccd7f7cbc0fe0ff345532fa2a/server/server.js#L30)):</sup>
Add this in addition to `.use(express.static('client'));`.
So CSS / compiled JS will be shipped correctly.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/211)

**Comment by saneyuki** [comment]
Review status: 8 of 13 files reviewed, 3 unresolved discussions, some commit checks pending.
Reviewed files:
- .gitignore @ r1
- client/__obj/.gitkeep @ r1
- client/index.html @ r1
- dist/client/__obj/.gitkeep @ r1
- dist/client/js/.gitkeep @ r1
- gulpfile.js @ r1
- index.js @ r1
- tsconfig.json @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/211)

**Comment by saneyuki** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- server/adapter/Package.js @ r2
- server/command-line/index.js @ r2
- server/Package.js @ r2
- server/plugins/irc-events/ctcp.js @ r2
- server/server.js @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/211)

**Comment by saneyuki** [comment]
r+

**Comment by Constellation** [comment]
Thank you!

**Pull request merged**
