### PR TITLE
Update option-t

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/260)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e32560f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e32560f with merge 5beae3b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/70541101)

**Pull request merged**
