### PR TITLE
Add tools/whitespace.txt

### PR DESCRIPTION
**Pull request by Constellation**
You may know https://github.com/google/skia/blob/master/whitespace.txt

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/393)

### CODE REVIEW

**Comment by Constellation** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0ca7d80 has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0ca7d80 with merge 54cc6ad...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/82454294)

**Pull request merged**
