### PR TITLE
feat(Rize): Add RizeNetworkSetDomain.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/577)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit fe50c55 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit fe50c55 with merge 3524970...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/109040388)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit c84b3f0 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit c84b3f0 with merge 3f56a34...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/109041469)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit b1f6e75 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit b1f6e75 with merge 67b6a70...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/109041728)

**Pull request merged**
