### PR TITLE
Use single quote in .eslintrc.js

### PR DESCRIPTION
**Pull request by saneyuki**
follow up #485

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/486)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d593aa7 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d593aa7 with merge f96cdbe...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/92404386)

**Pull request merged**
