### PR TITLE
refactor(build): rename to tools/build/script.js

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/597)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 23632cb has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 23632cb with merge 5680790...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/115028369)

**Pull request merged**
