### PR TITLE
Fix the regression by #635, #636

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/637)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 79da511 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 79da511 with merge 1da2e3d...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/127235060)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #637) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
