### PR TITLE
chore(typings): update d.ts

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/605)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 198c749 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 198c749 with merge 68aebbc...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/118141262)

**Pull request merged**
