### PR TITLE
Add the link to the commit bot page

### PR DESCRIPTION
**Pull request by Constellation**
Now, the commit bot is moved from my home server to OpenShift PaaS.
So, add the link to the commit bot.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/385)

### CODE REVIEW

**Comment by Constellation** [comment]
r=me

**Comment by Constellation** [comment]
r+

**Comment by Constellation** [comment]
r+

**Comment by Constellation** [comment]
r+

**Comment by Constellation** [comment]
Still work in progress.

**Comment by Constellation** [comment]
r+

**Comment by dokidokivisual** [comment]
Hello

**Comment by Constellation** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e8d0fb0 has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e8d0fb0 with merge ce0814e...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/82380155)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #385) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/82381272)

**Pull request merged**
