### PR TITLE
Add 'npm run tsc' to invoke typescript compilation phase.

### PR DESCRIPTION
**Pull request by saneyuki**
This target will be used casually like `npm run lint`.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/419)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7cc90da has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7cc90da with merge c3b2e0d...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/85488216)

**Pull request merged**
