### PR TITLE
update packages

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/585)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 63f53f7 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 63f53f7 with merge 752770b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/111376750)

**Pull request merged**
