### PR TITLE
Add some primitive logics to domain model.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/256)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 2ce8bde has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 2ce8bde with merge d82c8da...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/69646025)

**Pull request merged**
