### PR TITLE
refactor(test): add test config to manage origin

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/683)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 9ab6c0a has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 9ab6c0a with merge 17f8490...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/139015243)

**Pull request merged**
