### PR TITLE
Update glob to v6

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/457)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 78f4bbd has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 78f4bbd with merge f4f3204...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/90605536)

**Pull request merged**
