### PR TITLE
BREAKING CHANGE: refactor(config): use XDG_CONFIG_HOME dir to store the config

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/680)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual try

**Comment by dokidokivisual** [comment]
:hourglass: Trying commit d550bad with merge 6e6cdb6...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/138872081)

**Comment by Constellation** [comment]
@dokidokivisual r=me

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/680#-:-KKhXIsH-zjZPnovQUX3:275393782)*

**Comment by Constellation** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/680)*

**Comment by Constellation** [comment]
@dokidokivisual r=me

**Comment by saneyuki** [comment]
@dokidokivisual r=Constellation

**Comment by dokidokivisual** [comment]
:pushpin: Commit d550bad has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d550bad with merge 59bb74f...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/138879285)

**Pull request merged**
