### PR TITLE
Update cheerio version to 0.19.0

### PR DESCRIPTION
**Pull request by Constellation**
And test dokidokivisual commit bot.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/232)

### CODE REVIEW

**Comment by Constellation** [comment]
r+

**Comment by Constellation** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 12da21c has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 12da21c with merge 1d66162...

**Pull request merged**
