### PR TITLE
Update TypeScript compiler to v1.8.0-dev.20151114.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/465)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 51cb44b has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 51cb44b with merge ab333e7...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/91116643)

**Pull request merged**
