### PR TITLE
Replace from Handlebars template to React component

### PR DESCRIPTION
**Pull request by saneyuki**
retake #271, #273

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/274)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 54a036b has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 54a036b with merge 2606d49...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/71654153)

**Pull request merged**
