### PR TITLE
Revert "Pass 'NODE_ENV=production' when run 'npm run start'."

### PR DESCRIPTION
**Pull request by saneyuki**
- This reverts commit b0301c7dfc332ec002311f1489cdb726af6d4ff0.
- This commit is my miss pushing.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/291)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d5d44f0 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d5d44f0 with merge 089b999...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74422556)

**Pull request merged**
