### PR TITLE
Upgrade NodeJS to v5.x

### PR DESCRIPTION
**Pull request by saneyuki**
- https://nodejs.org/en/blog/release/v5.0.0/
- also upgrade npm to v3.x
   - ...also we need to specify npm version

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/442)

### CODE REVIEW

**Comment by saneyuki** [comment]
At this moment, `npm run gulp -- __eslint` dump the following error:

```sh
$ npm run gulp -- __eslint

> karen@0.0.0 gulp /src/js/karen-irc
> gulp "__eslint"

[11:08:59] Using gulpfile ~/src/js/karen-irc/gulpfile.js
[11:08:59] Starting '__eslint'...
/src/js/karen-irc/node_modules/estraverse/estraverse.js:517
                        throw new Error('Unknown node type ' + nodeType + '.');
                        ^

Error: Unknown node type ExportNamedDeclaration.
    at Controller.traverse (/src/js/karen-irc/node_modules/estraverse/estraverse.js:517:31)
    at EventEmitter.module.exports.api.verify (/src/js/karen-irc/node_modules/eslint/lib/eslint.js:779:24)
    at processText (/src/js/karen-irc/node_modules/eslint/lib/cli-engine.js:221:27)
    at processFile (/src/js/karen-irc/node_modules/eslint/lib/cli-engine.js:258:18)
    at executeOnFile (/src/js/karen-irc/node_modules/eslint/lib/cli-engine.js:604:23)
    at Array.forEach (native)
    at /src/js/karen-irc/node_modules/eslint/lib/cli-engine.js:630:49
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/src/js/karen-irc/node_modules/eslint/lib/cli-engine.js:626:18)
    at Object.cli.execute (/src/js/karen-irc/node_modules/eslint/lib/cli.js:159:95)
[11:08:59] '__eslint' errored after 587 ms
[11:08:59] Error: 1
    at formatError (/src/js/karen-irc/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/src/js/karen-irc/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/src/js/karen-irc/node_modules/orchestrator/index.js:264:8)
    at /src/js/karen-irc/node_modules/orchestrator/index.js:275:23
    at finish (/src/js/karen-irc/node_modules/orchestrator/lib/runTask.js:21:8)
    at /src/js/karen-irc/node_modules/orchestrator/lib/runTask.js:45:4
    at process._tickCallback (node.js:377:9)
```

this `estraverse`'s version is `v1.9.3`

**Comment by saneyuki** [comment]
dependency chain is:
`browserify@12.0.1` -> `module-deps@4.0.2` -> `detective@4.2.0` -> `escodegen@1.7.0` -> `estraverse@1.9.1`

**Comment by saneyuki** [comment]
> At this moment, npm run gulp -- __eslint dump the following error:

This problem is resolved by updating detective.

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 3cd1f6e has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 3cd1f6e with merge 65b3afc...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/88728634)

**Pull request merged**
