### PR TITLE
Enable many eslint rules

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/499)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+x

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 9a57321 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 9a57321 with merge a736493...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/93455311)

**Pull request merged**
