### PR TITLE
refactor(build): clean up

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/626)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 332312d has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 332312d with merge 78a775b...

**Comment by saneyuki** [comment]
@dokidokivisual r-

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/125486274)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit c975c05 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit c975c05 with merge fcc9bfc...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/125486515)

**Pull request merged**
