### PR TITLE
Fix a bug to not start karen as https supported server.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/468)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 860542c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 860542c with merge c9310c4...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/91138111)

**Pull request merged**
