### PR TITLE
Update typescript compiler to 1.8.0-dev.20160107

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/534)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 023bd8f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 023bd8f with merge 2ff77f6...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/100859977)

**Pull request merged**
