### PR TITLE
Move the logic to change the document's title to WindowPresenter

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/404)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 573e5fe has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 573e5fe with merge f6229a8...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/82774761)

**Pull request merged**
