### PR TITLE
refactor(build): move to babel-cli from gulp-babel

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/579)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e2753f2 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e2753f2 with merge 413db75...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/109684100)

**Pull request merged**
