### PR TITLE
test(FetchDriver): add more tests

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/703)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 8 of 11 files at r1, 2 of 5 files at r2.
Review status: 10 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/703)*

**Comment by saneyuki** [comment]
Reviewed 3 of 11 files at r1.
Review status: 10 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/703)*

**Comment by saneyuki** [comment]
Reviewed 2 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/703)*

**Comment by saneyuki** [comment]
r+

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/karen-irc/karen/703#-:-KLyJDGoXwjQeD9LIAH8:5174718)*

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 38252dc has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 38252dc with merge 0daff6a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/142653360)

**Pull request merged**
