### PR TITLE
chore(node): upgrade to node v6

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/630)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit ccdae09 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit ccdae09 with merge 40af265...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/126010786)

**Pull request merged**
