### PR TITLE
chore(lint): update eslint-plugin-react to 5.1.1

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/646)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit abb668f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit abb668f with merge 4b073a6...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/129038694)

**Pull request merged**
