### PR TITLE
Update typescript compiler to 1.8.0-dev.20151031

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/444)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 383ce84 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 383ce84 with merge fa1c3c8...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/88489600)

**Pull request merged**
