### PR TITLE
chore(package.json): update packages.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/591)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d5b2720 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d5b2720 with merge 3b5f135...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/113877652)

**Pull request merged**
