### PR TITLE
Use gulp-uglify instead of gulp-uglifyjs

### PR DESCRIPTION
**Pull request by saneyuki**
gulp-uglifyjs is deprecated.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/556)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 275ab8e has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 275ab8e with merge bfa3e1e...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/104017655)

**Pull request merged**
