### PR TITLE
Move to typings from tsd.

### PR DESCRIPTION
**Pull request by saneyuki**
https://github.com/typings/typings

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/563)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual try

**Comment by dokidokivisual** [comment]
:hourglass: Trying commit 68df2ea with merge 46323e2...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/105424463)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 68df2ea has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 68df2ea with merge 06f68cf...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/105425593)

**Pull request merged**
