### PR TITLE
Update eslint-plugin-react to 3.12

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/524)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7aa957f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7aa957f with merge 9e565a1...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/98044755)

**Pull request merged**
