### PR TITLE
chore(package.json): update eslint

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/702)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit ac7c4e7 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit ac7c4e7 with merge 1405ecf...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/142645081)

**Pull request merged**
