### PR TITLE
refactor(lint): enable tslint's no-default-export

### LINKED ISSUE #649: enable tslint's no-default-export

### PR DESCRIPTION
**Pull request by saneyuki**
Fix #649

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/663)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit a262a55 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit a262a55 with merge f71471f...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/133455945)

**Pull request merged**
