### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/541)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit f228f8b has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit f228f8b with merge 366ded8...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/102679587)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 002e361 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 002e361 with merge 3a4e4b3...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/102680594)

**Pull request merged**
