### PR TITLE
Use tslint's dev version

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/548)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit b873952 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit b873952 with merge 60e2414...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/103816559)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit a795d2c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit a795d2c with merge e4f980a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/103819764)

**Pull request merged**
