### PR TITLE
Change the source directory

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/553)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 378f565 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 378f565 with merge f029933...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/104004859)

**Pull request merged**
