### PR TITLE
refactor(build): add 'npm run build'

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/634)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 71d45bb has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 71d45bb with merge 3e286be...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/127172626)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 64513a2 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 64513a2 with merge 5fa3a67...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/127173522)

**Pull request merged**
