### PR TITLE
Use arrow functions in SocketIoDriver

### PR DESCRIPTION
**Pull request by Constellation**
|this| is used in the callback, but since it's not an arrow function,
|this| becomes unexpected value.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/257)

### CODE REVIEW

**Comment by Constellation** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 129415b has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 129415b with merge b251222...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/70266458)

**Pull request merged**
