### PR TITLE
Update eslint to 2.0.0-beta1

### PR DESCRIPTION
**Pull request by saneyuki**
http://eslint.org/blog/2016/01/eslint-v2.0.0-beta.1-released/

- [x] Update eslint to 2.0.0-beta1
- [x] Migrate keyword-spacing
- [x] 'sort-imports'
- [x] no-new-symbol
- [x] no-whitespace-before-property
- [x] no-useless-constructor
- [x] consistent-this
- [x] 'complexity'
- [x] 'no-bitwise'
- [x] func-style'
- [x] 'no-multiple-empty-lines'
- [x]  Use --no-ignore to override

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/540)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 5f055e3 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 5f055e3 with merge 7fcceef...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/101763912)

**Pull request merged**
