### PR TITLE
feat(server): add unhandledRejection handler

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/715)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit aa9bfd3 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit aa9bfd3 with merge eb4440e...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/144899347)

**Pull request merged**
