### PR TITLE
[client] Use HTMLElement.insertAdjacentHTML

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/418)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 88aa58d has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 88aa58d with merge a2a5c3a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/85615364)

**Pull request merged**
