### PR TITLE
[client] Move message dom node gc to MessageContentViewController

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/415)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit b8a9b79 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit b8a9b79 with merge 6bad651...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/84847914)

**Pull request merged**
