### PR TITLE
Add meta[name='referrer'] to prevent to send a referrer.

### PR DESCRIPTION
**Pull request by saneyuki**
This application could be hosted in non-public domain. There're some cases user don't want to leak any information about hosted domain.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/422)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0fec8d8 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0fec8d8 with merge 69479e2...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/85622074)

**Pull request merged**
