### PR TITLE
Use babel v6

### PR DESCRIPTION
**Pull request by saneyuki**
release note?
------------

- http://babeljs.io/blog/2015/10/29/6.0.0/

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/443)

### CODE REVIEW

**Comment by saneyuki** [comment]
build error:
```
$ npm run gulp -- __build:server

> karen@0.0.0 gulp /src/js/karen-irc
> gulp "__build:server"

[15:11:47] Using gulpfile /src/js/karen-irc/gulpfile.js
[15:11:47] Starting 'clean:server'...
[15:11:47] Finished 'clean:server' after 13 ms
[15:11:47] Starting '__babel:server'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: /src/js/karen-irc/server/Client.js: We found a path that isn't a NodePath instance
    at Function.get (/src/js/karen-irc/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/node_modules/babel-traverse/lib/path/index.js:103:13)
    at TraversalContext.create (/src/js/karen-irc/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/node_modules/babel-traverse/lib/context.js:73:30)
    at TraversalContext.visitMultiple (/src/js/karen-irc/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/node_modules/babel-traverse/lib/context.js:102:25)
    at TraversalContext.visit (/src/js/karen-irc/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/node_modules/babel-traverse/lib/context.js:193:19)
    at Function.traverse.node (/src/js/karen-irc/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/node_modules/babel-traverse/lib/index.js:139:17)
    at traverse (/src/js/karen-irc/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/node_modules/babel-traverse/lib/index.js:61:12)
    at Function.traverse.hasType (/src/js/karen-irc/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/node_modules/babel-traverse/lib/index.js:188:3)
    at BlockScoping.wrapClosure (/src/js/karen-irc/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:491:47)
    at BlockScoping.run (/src/js/karen-irc/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:383:12)
    at PluginPass.BlockStatementProgram (/src/js/karen-irc/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:96:24)
```

this may be https://github.com/babel/babel/issues/2644

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #451) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 70db1cf has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 70db1cf with merge ed9093e...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/90444329)

**Pull request merged**
