### PR TITLE
Upgrade eslint to 2.0.0-alpha-1 

### PR DESCRIPTION
**Pull request by saneyuki**
- #516
- http://eslint.org/blog/2015/12/eslint-v2.0.0-alpha-1-released/

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/518)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 1aa2d18 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 1aa2d18 with merge 8db8cb2...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/97097659)

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 1aa2d18 with merge 1dfe9ab...

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 1aa2d18 with merge d8c2ca2...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/97098844)

**Pull request merged**
