### PR TITLE
chore(EditorConfig): enable trim_trailing_whitespace for global

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/657)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 483217f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 483217f with merge 9244e2a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/132479861)

**Pull request merged**
