### PR TITLE
eslint: Enable rules which are recommended explicitly

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/500)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 02a1464 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 02a1464 with merge cbc4916...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/93466609)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 1dbbbc9 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 1dbbbc9 with merge 0f5ea21...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/93466697)

**Pull request merged**
