### PR TITLE
Re-enable tsc's noImplicitReturns option

### LINKED ISSUE #503: Re-enable 'noImplicitReturns' of TypeScript compiler's option
By https://github.com/Microsoft/TypeScript/pull/5733, typescript compiler's `noImplicitReturns` option checks all functions including all callbacks.

At this moment, we should not fix our code to apply the option because its rules may change until shipping it in stable. However, we need to fix this in some future.

### PR DESCRIPTION
**Pull request by saneyuki**
Fix #503

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/511)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 91a85d6 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 91a85d6 with merge ae71bda...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/94313394)

**Pull request merged**
