### PR TITLE
Test r=me for dokidokivisual commit bot

### PR DESCRIPTION
**Pull request by Constellation**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/396)

### CODE REVIEW

**Comment by Constellation** [comment]
@dokidokivisual r=me

**Comment by dokidokivisual** [comment]
:pushpin: Commit f9666e3 has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit f9666e3 with merge 148eccb...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/82466169)

**Pull request merged**
