### PR TITLE
chore(package.json): update packages.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/670)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0efade1 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0efade1 with merge d21c4e1...

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0efade1 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/136899017)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e629ff9 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e629ff9 with merge 6922542...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/136899624)

**Pull request merged**
