### PR TITLE
Update ESLint to 0.23.x

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/243)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 891e456 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 891e456 with merge d480c0b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/67143238)

**Comment by Constellation** [comment]
__NOTE:__
dokidokivisual commit bot & travis CI are very quick because I added `node_modules` into cached directories in travis CI. It's OK because `npm install` perform onto the cached directory.

But, if the dependent modules take non-good behavior (like force updating the same version with the momdified source), it will be broken. When you have some troubles about cached node modules, let's clean the cache in travis CI. It can be done through travis CI's project page.

**Pull request merged**
