### PR TITLE
chore(package.json): update typescript compiler

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/651)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 8a3a539 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 8a3a539 with merge c3b8e78...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/130541614)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #651) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
