### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/502)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 3ade4b6 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 3ade4b6 with merge d48f5e8...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/93769488)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 2675d08 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 2675d08 with merge 48d5b40...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/93771694)

**Pull request merged**
