### PR TITLE
chore(package.json): update packages

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/608)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit a0fdc1a has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit a0fdc1a with merge a137c0e...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/120010330)

**Pull request merged**
