### PR TITLE
chore(package.json): specify libs definitions

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/716)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit ab0d8f8 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit ab0d8f8 with merge 5af2bfc...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/145048234)

**Pull request merged**
