### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/535)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 8305c3a has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 8305c3a with merge 1413977...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/101266180)

**Pull request merged**
