### PR TITLE
doc(ViewContext): add some my concern to the future

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/586)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 8fb699a has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 8fb699a with merge 3a6ae32...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/112011397)

**Pull request merged**
