### PR TITLE
chore(EditorConfig): enable 'insert_final_newline = true'

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/656)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 216e17b has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 216e17b with merge 537b780...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/132477970)

**Pull request merged**
