### PR TITLE
fix(ESLint): Disable sort-imports explicitly

### LINKED ISSUE #539: lint: Enable sort-imports

### PR DESCRIPTION
**Pull request by saneyuki**
Fix #539

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/621)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 5b7dbab has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 5b7dbab with merge d879a54...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/123949834)

**Pull request merged**
