### PR TITLE
chore(package.json): update packages

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/617)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 08ed82f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 08ed82f with merge 7521a8c...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/122720633)

**Pull request merged**
