### PR TITLE
fix(ESLint): enable no-use-before-define

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/620)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 41aa5a3 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 41aa5a3 with merge 6a6fe6f...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/123854461)

**Pull request merged**
