### PR TITLE
server: Enable some HTTP security header

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/480)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7063e44 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7063e44 with merge 37168d2...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/92195363)

**Pull request merged**
