### PR TITLE
Enable some tslint rules

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/411)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d1a6fb5 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d1a6fb5 with merge 76d85a1...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/84722434)

**Pull request merged**
