### PR TITLE
refactor(ConnectSetting): define a viewmodel for handle a 'micro' event

### PR DESCRIPTION
**Pull request by saneyuki**
To notify a view only events, `intent` is a bit large scale.

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/643)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 1fcd315 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 1fcd315 with merge 6ec6464...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/127975895)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #643) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
