### PR TITLE
Move the part of partFromChannel for Sidebar.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/247)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 094cebd has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 094cebd with merge 38cdb51...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/68464693)

**Pull request merged**
