### PR TITLE
chore(package.json): update eslint to 2.1.0

### PR DESCRIPTION
**Pull request by saneyuki**
http://eslint.org/blog/2016/02/eslint-v2.0.0-released

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/576)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit f8bc66c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit f8bc66c with merge 9ca6007...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/109507542)

**Pull request merged**
