### PR TITLE
Update TypeScript compiler to 1.8.0-dev.20160117

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/542)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7c643a1 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7c643a1 with merge ccd1a4d...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/102963710)

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7c643a1 with merge a395a9a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/102964205)

**Pull request merged**
