### PR TITLE
Add branch blacklist for "tmp" branch in travis CI

### PR DESCRIPTION
**Pull request by Constellation**
This branch is used in homu. And should not run CI.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/238)

### CODE REVIEW

**Comment by Constellation** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 10d2665 has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 10d2665 with merge 955a3ea...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/66090006)

**Pull request merged**
