### PR TITLE
Fix the build fails on Windows.

### LINKED ISSUE #240: karen's build is failed on Windows.
e.g.

```sh
$ gulp jslint
[20:37:45] Using gulpfile ~\src\karen\gulpfile.js
[20:37:45] Starting 'jslint'...
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: spawn ~\src\karen\node_modules\.bin\eslint ENOENT
    at exports._errnoException (util.js:846:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:177:32)
    at onErrorNT (internal/child_process.js:343:16)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:117:18)
    at node.js:946:3
```

### PR DESCRIPTION
**Pull request by saneyuki**
Fix #240

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/241)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit aa1f824 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit aa1f824 with merge 5b04db2...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/66847154)

**Pull request merged**
