### PR TITLE
client: Display notable messages for reactified sidebar

### PR DESCRIPTION
**Pull request by saneyuki**
see also: #191

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/484)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 6 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/484)_

**Comment by saneyuki** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/484)_

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e930766 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e930766 with merge da41183...

**Comment by saneyuki** [comment]
@dokidokivisual r=

**Comment by dokidokivisual** [comment]
:pushpin: Commit e930766 has been approved by ``

**Comment by saneyuki** [comment]
@dokidokivisual r-

**Pull request merged**
