### PR TITLE
chore(package.json): update eslint

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/666)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 5b41d69 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 5b41d69 with merge bef70f2...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/134003396)

**Pull request merged**
