### PR TITLE
[server] Construct csp directive from Map<K, V> instead of object bag.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/275)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit ace833b has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit ace833b with merge 535b8d5...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/71658017)

**Pull request merged**
