### PR TITLE
Upgrade eslint to 2.0.0-alpha2

### PR DESCRIPTION
**Pull request by saneyuki**
- #516
- http://eslint.org/blog/2015/12/eslint-v2.0.0-alpha-2-released/

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/527)

### CODE REVIEW

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #528) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@dokidokivisual try

**Comment by dokidokivisual** [comment]
:lock: Merge conflict

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #538) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 21d6311 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 21d6311 with merge 6c603d7...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/101754558)

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 21d6311 with merge f7fea79...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/101754695)

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 21d6311 with merge a007ad3...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/101754903)

**Pull request merged**
