### PR TITLE
chore(package.json): update packages.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/603)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7510d1a has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7510d1a with merge 89522de...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/117643126)

**Pull request merged**
