### PR TITLE
feat(tslint): unify type assertion syntax with `as` syntax

### PR DESCRIPTION
**Pull request by saneyuki**
By historicaly, TypeScript has two type assertion syntax:

* `<Foo>Bar` is introduced from classically.a
* `Bar as Foo` is introduced with React JSX syntax.

At now, there are no recommendation style.

> The two samples are equivalent. Using one over the other is mostly a
> choice of preference; however, when using TypeScript with JSX, only
> as-style assertions are allowed.
> http://www.typescriptlang.org/docs/handbook/basic-types.html

But in this project, we unify them into `as` syntax.

This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/613)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0fe83c9 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0fe83c9 with merge f50e110...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/120813291)

**Pull request merged**
