### PR TITLE
 test to invoke homu

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/678)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual try

**Comment by saneyuki** [comment]
@dokidokivisual try=saneyuki

**Comment by Constellation** [comment]
@dokidokivisual try

**Comment by Constellation** [comment]
@dokidokivisual try=Constellation

**Comment by Constellation** [comment]
@dokidokivisual r=me

**Comment by Constellation** [comment]
Hm, it seems that GitHub's webhook is not sent, correct?

@dokidokivisual try

**Comment by dokidokivisual** [comment]
:hourglass: Trying commit 9e59866 with merge 13264bb...

**Comment by Constellation** [comment]
Recovered. Okaeri, Syaro-chang!

**Comment by saneyuki** [comment]
yay!

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/138861844)

**Pull request closed without merging**
