### PR TITLE
[client] Remove Mousetrap dependency 

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/296)

### CODE REVIEW

**Comment by saneyuki** [comment]
@Constellation r?

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #299) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 8d82584 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 8d82584 with merge 6f0fdc2...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74531347)

**Pull request merged**
