### PR TITLE
Update TypeScript Compiler to 816cfe3ec6c879fd912f24d5b87130d9cb7fa1b2

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/262)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d5f5b03 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d5f5b03 with merge 025abdd...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/70937102)

**Pull request merged**
