### PR TITLE
Remove unused test infrastructure

### PR DESCRIPTION
**Pull request by saneyuki**
This is completely meaningless

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/554)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 967ffbc has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 967ffbc with merge 640d910...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/104005385)

**Pull request merged**
