### PR TITLE
Start Project Rize

### PR DESCRIPTION
**Pull request by saneyuki**
Project Rize is to _ReInitialiZE (reinitialize)_ our application.

This project targets to bootstrap our next code base.

- Responsible Interface
- Ignite Performance
- Zero gravity from legacy style
- Empower a client

## How to build

- We use `ENABLE_RIZE` environment variable as the build flag for Rize build.
- `env ENABLE_RIZE=1 npm start`

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/549)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/549)*

**Comment by saneyuki** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/549)*

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0e321bf has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0e321bf with merge ebbc408...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/103895312)

**Pull request merged**
