### PR TITLE
Update babel to v6.4

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/533)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 07659b2 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 07659b2 with merge 0b19c67...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/100850916)

**Pull request merged**
