### PR TITLE
Specify NodeJS version loosely

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/519)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 9f1042d has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 9f1042d with merge 258fd7b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/97099571)

**Pull request merged**
