### PR TITLE
[client] Add 'js-' prefix to attribute values which are touched from script

### PR DESCRIPTION
**Pull request by saneyuki**
#153

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/297)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 738e138 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 738e138 with merge 7bcd090...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74454678)

**Pull request merged**
