### PR TITLE
Update typescript related packages

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/564)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r_

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit b8c1638 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit b8c1638 with merge 120d790...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/105428841)

**Pull request merged**
