### PR TITLE
client: Rewrite client's sidebar view with using React

### LINKED ISSUE #191: Rewrite client's sidebar view with using React
- I seem It's reasonable to use React.
- But this need to resolve to implement DnD sortable sidebar.

### PR DESCRIPTION
**Pull request by saneyuki**
- Fix #191
- This also removes the drag & drop feature in sidebar to sort items.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/492)

### CODE REVIEW

**Comment by saneyuki** [comment]
@Constellation r?

**Comment by Constellation** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/script/karen.ts, line 6 \[r1\]](https://reviewable.io:443/reviews/karen-irc/karen/492#-K3zDe0dCnqD8mNjki9-:-K3zDe0dCnqD8mNjki90:1460179469) ([raw file](https://github.com/karen-irc/karen/blob/62aab054188d203d265aab1908176fa588ec5104/client/script/karen.ts#L6)):*
Nice :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/492)*

**Comment by Constellation** [comment]
Looks nice. r+

---

Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/492#-:-K3zGhmEySoJGBhnrgKY:345325913)*

**Comment by saneyuki** [comment]
@Constellation 

Thank you review!
I think our next milestone would be following things like slack:

- mark/unmark your favorite channel.
- sort channels in sidebar alphabetically.
- search & jump channels like spotlight.

How do you think? Do you have any other features?

**Comment by Constellation** [comment]
Sounds nice.
And I think persistent layer to reduce memory consumption for long-live karen instance is good goal.
What do you think of?

**Comment by saneyuki** [comment]
> And I think persistent layer to reduce memory consumption for long-live karen instance is good goal.

sounds good.
I'll wrote some of my thoughts about it to #266

**Comment by saneyuki** [comment]
@dokidokivisual r=Constellation

**Comment by dokidokivisual** [comment]
:pushpin: Commit a9dce78 has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit a9dce78 with merge 06eef57...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/93187009)

**Pull request merged**
