### PR TITLE
chore(package.json): update typescript

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/659)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 1bc1007 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 1bc1007 with merge a8b91f3...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/133004713)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #659) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
