### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/526)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit abec853 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit abec853 with merge d6e00f3...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/98633992)

**Pull request merged**
