### PR TITLE
chore(eslint): update eslint to 2.0.0-beta.2

### PR DESCRIPTION
**Pull request by saneyuki**
http://eslint.org/blog/2016/01/eslint-v2.0.0-beta.2-released/

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/560)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit e5d435d has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e5d435d with merge 6f77928...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/104330706)

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit e5d435d with merge 743d11a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/104331046)

**Pull request merged**
