### PR TITLE
Update eslint-plugin-react to v3.0.x

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/281)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 908a470 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 908a470 with merge 3f3444d...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/72765815)

**Pull request merged**
