### PR TITLE
[client] Move from Handlebars to React

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/277)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 2 of 2 files at r1, 8 of 8 files at r2, 5 of 8 files at r3, 1 of 2 files at r4, 2 of 3 files at r5, 5 of 9 files at r6, 2 of 4 files at r7, 2 of 3 files at r8, 2 of 2 files at r9, 5 of 5 files at r10.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/277)

**Comment by saneyuki** [comment]
Reviewed 2 of 2 files at r12.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/277)

**Comment by saneyuki** [comment]
Reviewed 14 of 14 files at r13.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/277)

**Comment by saneyuki** [comment]
Reviewed 2 of 2 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/277)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7af2cf1 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7af2cf1 with merge 6fd4d0c...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/73703915)

**Pull request merged**
