### PR TITLE
Fix the resgression of #450

### PR DESCRIPTION
**Pull request by saneyuki**
Fix the resgression of #450

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/466)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 82787e5 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 82787e5 with merge d8a315b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/91119117)

**Pull request merged**
