### PR TITLE
Upgrade RxJS to v5

### LINKED ISSUE #517: Upgrade RxJS to v5
v5 is still in beta. but this change will be big change.

## related documents

- https://github.com/ReactiveX/RxJS/blob/master/CHANGELOG.md#500-beta0-2015-12-15
- https://github.com/ReactiveX/RxJS/blob/master/MIGRATION.md

### PR DESCRIPTION
**Pull request by saneyuki**
Fix #517 

## changed terminology

- Observer -> Subscriber
- Disposable -> Subscription

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/520)

### CODE REVIEW

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #530) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 97e2ba7 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 97e2ba7 with merge b355b6a...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/102004143)

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 97e2ba7 with merge 9e1dbfb...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/102004667)

**Pull request merged**
