### PR TITLE
feat(Rize): Add NotificationService

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/557)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit cc7f709 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit cc7f709 with merge fde0072...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/104046601)

**Pull request merged**
