### PR TITLE
refactor(server): split middleware for security

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/638)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit a671169 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit a671169 with merge 8b22a94...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/127593928)

**Pull request merged**
