### PR TITLE
refactor(settings): Convert jsx -> tsx

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/696)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 63b6844 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 63b6844 with merge 0533ff1...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/141611060)

**Pull request merged**
