### PR TITLE
Update TypeScript compiler to v1.8.0-dev.20151027

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/439)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit abd4013 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit abd4013 with merge b445f0e...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/87807529)

**Pull request merged**
