### PR TITLE
chore(jsconfig.json): remove 'target' option which is deprecated from v0.10.10

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/587)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit ae6ccd2 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit ae6ccd2 with merge 5014509...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/112768278)

**Pull request merged**
