### PR TITLE
Update react to 0.14.3

### PR DESCRIPTION
**Pull request by saneyuki**
http://facebook.github.io/react/blog/2015/11/18/react-v0.14.3.html

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/476)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit cba917c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit cba917c with merge e3380fa...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/91962706)

**Pull request merged**
