### PR TITLE
tslint: Use 3.2.1-dev.1

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/525)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 87fd22d has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 87fd22d with merge 8254863...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/98046245)

**Pull request merged**
