### PR TITLE
Enable more tslint's options

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/505)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 3559413 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 3559413 with merge 33b6beb...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/93809406)

**Pull request merged**
