### PR TITLE
Use react.d.ts files hosted in DefinitelyTyped.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/474)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit aa097a5 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit aa097a5 with merge 64c2829...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/91866394)

**Pull request merged**
