### PR TITLE
server: Use os.homedir().

### PR DESCRIPTION
**Pull request by saneyuki**
This api is introduced since iojs v2.3.0
https://github.com/nodejs/node/blob/v2.3.0/CHANGELOG.md

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/509)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit cfc7c95 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit cfc7c95 with merge c421606...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/94101922)

**Pull request merged**
