### PR TITLE
feat(TypeScript): enable noUnusedParameters option

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/707)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d43f927 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d43f927 with merge 4697312...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/142988422)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 458fcd5 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 458fcd5 with merge 7f2754f...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/142989686)

**Pull request merged**
