### PR TITLE
refactor(client): separate 'settings' bounded context

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/645)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7c62c9c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7c62c9c with merge 1c8cdd0...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/128681577)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #645) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
