### PR TITLE
Bump node.js version to 4.1

### PR DESCRIPTION
**Pull request by Constellation**
Now, node.js 4.1 is stable.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/386)

### CODE REVIEW

**Comment by Constellation** [comment]
@dokidokivisual r=me

**Comment by Constellation** [comment]
@dokidokivisual r+

**Comment by Constellation** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 666c2ad has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 666c2ad with merge 988b2fd...

**Pull request merged**
