### PR TITLE
feat(ViewContextStack): implement ViewContextStack

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/668)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual try

**Comment by saneyuki** [comment]
@dokidokivisual try

**Comment by dokidokivisual** [comment]
:hourglass: Trying commit 85e9217 with merge 2d53eaf...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/138867271)

**Comment by Constellation** [comment]
Let's check cq works correctly. @dokidokivisual try!

**Comment by Constellation** [comment]
@dokidokivisual try

**Comment by dokidokivisual** [comment]
:hourglass: Trying commit 067b814 with merge b9cf5c5...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/140716981)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 836a139 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 836a139 with merge 03286b9...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/142696709)

**Pull request merged**
