### PR TITLE
[client] Use enum to represet CurrentTabType.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/278)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 5351ff1 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 5351ff1 with merge bc2ea02...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/71812414)

**Pull request merged**
