### PR TITLE
feat(tslint): enable 'no-any' rule

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/725)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 6e82011 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 6e82011 with merge af1b344...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/149658682)

**Pull request merged**
