### PR TITLE
Update TypeScript compiler to 1.6.0-dev.20150806

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/295)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit fb3635b has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit fb3635b with merge 8fce24b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74438875)

**Pull request merged**
