### PR TITLE
Update browserify to v12.x

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/438)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 85c0f0c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 85c0f0c with merge a79bcdf...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/87604213)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #438) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
