### PR TITLE
chore(package.json): update packages

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/595)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit da9b03a has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit da9b03a with merge fc53483...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/115025483)

**Pull request merged**
