### PR TITLE
feat(Rize): introduce Context

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/642)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 894afbe has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 894afbe with merge 84531d8...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/127816762)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #642) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
