### PR TITLE
refactor(server): create 'KarenServer' class

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/639)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 759a3b9 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 759a3b9 with merge ea17f5a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/127610578)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #639) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
