### PR TITLE
Update eslint-plugin-react to v3.5.x

### PR DESCRIPTION
**Pull request by saneyuki**
- Enable `no-direct-mutation-state`.
- Don't enable `forbid-prop-types`.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/402)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 2749540 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 2749540 with merge e8621dc...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/82763193)

**Pull request merged**
