### PR TITLE
feat(tsc): Specify tsc's new options

### LINKED ISSUE #571: Enable tsc's noFallthroughCasesInSwitch option

### PR DESCRIPTION
**Pull request by saneyuki**
Fix #571

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/572)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 8a1c40c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 8a1c40c with merge 83f173c...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/107705916)

**Pull request merged**
