### PR TITLE
server: Use HTTP2 (or SPDY) protocol when TLS is enabled

### PR DESCRIPTION
**Pull request by saneyuki**
- We use https://github.com/indutny/node-spdy
- This has not been worked server push yet.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/473)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/473)_

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 8bda1b5 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 8bda1b5 with merge 15cabda...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/91838148)

**Pull request merged**
