### PR TITLE
Update TypeScript compiler & linter

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/498)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 30c6842 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 30c6842 with merge c773a81...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/93287150)

**Pull request merged**
