### PR TITLE
chore(package.json): update depndencies

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/698)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 27a866b has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 27a866b with merge 1760085...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/142029934)

**Pull request merged**
