### PR TITLE
chore(vscode): specify to use local tsserver via settings.json

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/719)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 1c14825 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 1c14825 with merge ce3a055...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/145053548)

**Pull request merged**
