### PR TITLE
chore(package.json): update packages.

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/650)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 32e3f6a has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 32e3f6a with merge 0d28fe1...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/130539020)

**Pull request merged**
