### PR TITLE
Update dependencies explicitly

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/420)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 297f9ec has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 297f9ec with merge a478640...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/85615620)

**Pull request merged**
