### PR TITLE
[client] Render ConnectSettingWindow in client side

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/279)

### CODE REVIEW

**Comment by saneyuki** [comment]
Reviewed 2 of 2 files at r1.
Review status: 2 of 10 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/279)

**Comment by saneyuki** [comment]
Reviewed 2 of 2 files at r2.
Review status: 4 of 10 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/279)

**Comment by saneyuki** [comment]
Reviewed 4 of 6 files at r3.
Review status: 8 of 10 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/279)

**Comment by saneyuki** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[client/script/output/view/ConnectSettingWindow.js, line 27 \[r3\]](https://reviewable.io:443/reviews/karen-irc/karen/279#-Juh7QREfjU7fwt9E67J)** ([raw file](https://github.com/karen-irc/karen/blob/859d1a242e5b45d8b12ade3f87a08c529a06575f/client/script/output/view/ConnectSettingWindow.js#L27)):</sup>
don't use state.

---

<sup>**[client/script/output/view/ConnectSettingWindow.js, line 100 \[r3\]](https://reviewable.io:443/reviews/karen-irc/karen/279#-Juh7Lk4_3GIgudBpAgd)** ([raw file](https://github.com/karen-irc/karen/blob/859d1a242e5b45d8b12ade3f87a08c529a06575f/client/script/output/view/ConnectSettingWindow.js#L100)):</sup>
we need to handle checkbox as special case.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/279)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #281) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
Reviewed 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[client/script/output/viewmodel/ConnectionStore.ts, line 35 \[r5\]](https://reviewable.io:443/reviews/karen-irc/karen/279#-JvcDHoTk5OPUkecCQwT)** ([raw file](https://github.com/karen-irc/karen/blob/5cfa2e514495746267efab0372518e33128255db/client/script/output/viewmodel/ConnectionStore.ts#L35)):</sup>
this should be `state`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/279)

**Comment by saneyuki** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/karen-irc/karen/279)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 0e5a345 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 0e5a345 with merge 793361b...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/73665062)

**Pull request merged**
