### PR TITLE
fix(lint): fix warn/error

### PR DESCRIPTION
**Pull request by saneyuki**
relate #646

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/647)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 46f0438 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 46f0438 with merge 2624359...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/129099178)

**Pull request merged**
