### PR TITLE
chore(package.json): update dependencies

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/722)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit cc53c12 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit cc53c12 with merge f73fa18...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/148552782)

**Pull request merged**
