### PR TITLE
Remove some unused imports.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/403)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit c269640 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit c269640 with merge e945e87...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/82769326)

**Pull request merged**
