### PR TITLE
Update React to v0.14.2

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 8406096 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 8406096 with merge e012e05...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/88928185)

**Pull request merged**
