### PR TITLE
server: Enable 'X-Frame-Options:DENY'

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/475)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit a1cb249 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit a1cb249 with merge 395dd8a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/91881421)

**Pull request merged**
