### PR TITLE
chore(package.json): update eslint

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/682)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual try

**Comment by dokidokivisual** [comment]
:hourglass: Trying commit ad45e16 with merge 72a4c4c...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/138997537)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit ad45e16 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit ad45e16 with merge 4db5713...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/138998410)

**Pull request merged**
