### PR TITLE
Add babel-core as dev dependency explicitly.

### PR DESCRIPTION
**Pull request by saneyuki**
This change gives us to specify the version of babel-core.

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/249)

### CODE REVIEW

**Comment by saneyuki** [comment]
@Constellation r?

**Comment by Constellation** [comment]
lgtm

@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 9defbdd has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 9defbdd with merge 1f4e465...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/69320055)

**Pull request merged**
