### PR TITLE
Update core-js to v1.0.x

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/283)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d360b57 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d360b57 with merge cdca9e0...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/73695752)

**Pull request merged**
