### PR TITLE
Remove needless lodash

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/270)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 068d3ce has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 068d3ce with merge 1104975...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/71617692)

**Pull request merged**
