### PR TITLE
Add david-dm.org's dependency badges

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/397)

### CODE REVIEW

**Comment by Constellation** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 873e138 has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 873e138 with merge a491d93...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/83056483)

**Pull request merged**
