### PR TITLE
fix(ExIterable): specialized map should not take over index from filter

### PR DESCRIPTION
**Pull request by saneyuki**
The bug fix which is introduced by #692

---
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/693)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 04c4c2d has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 04c4c2d with merge 175e0f4...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/140250174)

**Pull request merged**
