### PR TITLE
refactor(server/): stop default export

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/636)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit c097f6c has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit c097f6c with merge 3e8fb92...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/127183111)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #636) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
