### PR TITLE
feat(FetchDriver): implement FetchDriver.origin()

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/706)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit f916ad6 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit f916ad6 with merge 3754d05...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/142707629)

**Pull request merged**
