### PR TITLE
Update babel packages

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/497)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 30b4144 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 30b4144 with merge 57c1570...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/93189169)

**Pull request merged**
