### PR TITLE
chore(package.json): update dependencies

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/615)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 6a3cfd2 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 6a3cfd2 with merge 3399e27...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/121906003)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 7dda595 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 7dda595 with merge 75f39f1...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/121908563)

**Pull request merged**
