### PR TITLE
Enable some TypeScript compiler option

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/489)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 89f2d47 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 89f2d47 with merge dffefaa...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/92449831)

**Pull request merged**
