### PR TITLE
chore(package.json): update dependencies

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/721)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 5ebd3eb has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 5ebd3eb with merge d87eafe...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/146817811)

**Pull request merged**
