### PR TITLE
chore(eslint): add .eslintignore

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/685)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 9612ad6 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 9612ad6 with merge 833d925...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/139399448)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit cec7a77 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit cec7a77 with merge c7faada...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/139399828)

**Pull request merged**
