### PR TITLE
feat(lib): add extensions for ECMA262's iterator

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/660)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit f7513dc has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit f7513dc with merge faa107c...

**Comment by saneyuki** [comment]
@dokidokivisual r-

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit f7513dc has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/133439065)

**Pull request merged**
