### PR TITLE
Lint related misc work

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/544)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 2c57135 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 2c57135 with merge 2d8d286...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/103045001)

**Pull request merged**
