### PR TITLE
Fix some warning

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/300)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit fdaadfa has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit fdaadfa with merge bb225f4...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74535597)

**Pull request merged**
