### PR TITLE
chore(package.json): update

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/593)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 558a9e3 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 558a9e3 with merge bacbbd5...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/114272411)

**Pull request merged**
