### PR TITLE
Update option-t to v0.15

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/449)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit f04206d has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit f04206d with merge 407fa4a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/89044978)

**Pull request merged**
