### PR TITLE
Update typescript compiler to v1.6.0-dev.20150814

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/303)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit c0a4a07 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit c0a4a07 with merge 37f59b2...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/75670154)

**Pull request merged**
