### PR TITLE
Update tsc to 1.8.0-dev.20151204

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/514)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 6ea0f05 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 6ea0f05 with merge b9f9181...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/95140552)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit c13b326 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit c13b326 with merge e702796...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/95140654)

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 1fe55fc has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 1fe55fc with merge 38aa45f...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/95140830)

**Pull request merged**
