### PR TITLE
refactor(eslint): split .eslintrc.js

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/671)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit aab3fab has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit aab3fab with merge 870724f...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/136901570)

**Pull request merged**
