### PR TITLE
fix: Uncaught TypeError: Cannot read property 'dispatcher' of undefined

### PR DESCRIPTION
**Pull request by saneyuki**
Fix the regression by #663

This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/669)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 14f2a1d has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 14f2a1d with merge 1ede384...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/135777744)

**Pull request merged**
