### PR TITLE
refactor(ExIterable): teach a 'source' iterable to Operator

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/691)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit f215304 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit f215304 with merge a371d64...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/140244622)

**Pull request merged**
