### PR TITLE
fix(lint): suppress warnings

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/559)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit b169647 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit b169647 with merge 07b2252...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/104326502)

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #559) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
