### PR TITLE
chore(package.json): update packages.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/568)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit bc21cfd has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit bc21cfd with merge e933f37...

**Comment by dokidokivisual** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/karen-irc/karen/builds/106436989)

**Comment by saneyuki** [comment]
@dokidokivisual retry

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit bc21cfd with merge c79ffb1...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/106437311)

**Pull request merged**
