### PR TITLE
Update Rx to v4.x

### PR DESCRIPTION
**Pull request by saneyuki**
https://github.com/Reactive-Extensions/RxJS/releases/tag/v4.0.0

[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/381)

### CODE REVIEW

**Comment by saneyuki** [comment]
I found some regressions which we need to wait to resolve:

- https://github.com/Reactive-Extensions/RxJS/issues/931

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #420) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit bb5ac0f has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit bb5ac0f with merge b77c89d...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/91116027)

**Pull request merged**
