### PR TITLE
Remove the lock effect from connect button.

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/246)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 91f8af8 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 91f8af8 with merge 00f13ec...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/68308584)

**Pull request merged**
