### PR TITLE
chore(package.json): update dependencies

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/654)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit db078d4 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit db078d4 with merge 4129e9a...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/131954785)

**Pull request merged**
