### PR TITLE
Lint /client/.eslintrc.js

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/522)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit d736429 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit d736429 with merge 4dbb764...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/97379160)

**Pull request merged**
