### PR TITLE
Update eslint-plugin-react to v3.2.x

### PR DESCRIPTION
**Pull request by saneyuki**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/288)

### CODE REVIEW

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably #265) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 5f76da8 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 5f76da8 with merge 41934c7...

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/74531477)

**Pull request merged**
