### PR TITLE
Update moment library

### PR DESCRIPTION
**Pull request by Constellation**
[Review on Reviewable](https://reviewable.io/reviews/karen-irc/karen/234)

### CODE REVIEW

**Comment by Constellation** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit 9fa28af has been approved by `Constellation`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit 9fa28af with merge e2630e3...

**Comment by Constellation** [comment]
@dokidokivisual rollup

**Comment by dokidokivisual** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/karen-irc/karen/builds/66080834)

**Pull request merged**
