### PR TITLE
Remove rize dir

### PR DESCRIPTION
**Pull request by saneyuki**
This change is [Reviewable](https://reviewable.io/reviews/karen-irc/karen/727)

### CODE REVIEW

**Comment by saneyuki** [comment]
@dokidokivisual r+

**Comment by dokidokivisual** [comment]
:pushpin: Commit f14ab32 has been approved by `saneyuki`

**Comment by dokidokivisual** [comment]
:hourglass: Testing commit f14ab32 with merge 7be8756...

**Comment by dokidokivisual** [comment]
:umbrella: The latest upstream changes (presumably 9e2e0cb) made this pull request unmergeable. Please resolve the merge conflicts.

**Pull request merged**
